name = "backend"
compatibility_date = "2023-12-01"

[vars]

DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiN2E0Y2ZhOWMtYjBjZC00MzNiLTg3ZDYtNDA4NDIzMDY3MDhiIiwidGVuYW50X2lkIjoiMDEwNjI3ZDFmNmFjZGU2ODFhNjM0ZTMxZTI2MGRhMjE3MzVlMDg4OTNjNzNhZjQ3YWI2MmVlMjk4MGFlMDY0YyIsImludGVybmFsX3NlY3JldCI6ImIyNjgwZWQyLTMwMGMtNGY3NS04OTUwLTNkNWM4NDlmOGQxMiJ9.BRgLcIPL7PhP09voUNw4-tdAIts7xne17gPXBBYZeb8"
